### PR TITLE
Fix #99 prevent S3 overwrite files

### LINKED ISSUE #99: S3 overwrite settings
When S3 storage is set, files may be overwritten if uploaded with the same name and path

### PR DESCRIPTION
**Pull request by trottomv**

### CODE REVIEW

**Comment by pauloxnet** [comment]
Please add the new settings also in env template file.

**Comment by trottomv** [comment]
the other s3 settings aren't in the env_template file

> Please add the new settings also in env template file.

**Comment by pauloxnet** [comment]
> the other s3 settings aren't in the env_template file, maybe in the backend.yaml ?

Yes

**Comment by trottomv** [comment]
> Please add the new settings also in env template file.

done

**Comment by pauloxnet** [comment]
Can you add the new variable in https://github.com/20tab/20tab-standard-project ?

**Comment by trottomv** [comment]
> Can you add the new variable in https://github.com/20tab/20tab-standard-project ?

done

**Pull request merged**
